FROM docker.io/rayproject/ray:2.44.1-py312 

USER root
RUN chown ray:root /home/ray && chmod g=u /home/ray
COPY models /models
USER ray

RUN pip install --upgrade --no-cache-dir pip 

# set up environment required to install and use huggingface and fasttext
USER root
RUN apt update && sudo apt install gcc g++ cmake -y
USER ray

# install pytest
RUN pip install --no-cache-dir pytest
ARG DPK_WHEEL_FILE_NAME
ARG TRANSFORM_NAME

# Copy and install data processing libraries 
# These are expected to be placed in the docker context before this is run (see the make image).
COPY --chmod=775 --chown=ray:root data-processing-dist data-processing-dist
RUN pip install --no-cache-dir data-processing-dist/${DPK_WHEEL_FILE_NAME}[ray]

COPY --chmod=775 --chown=ray:root dpk_${TRANSFORM_NAME}/ dpk_${TRANSFORM_NAME}/
COPY --chown=ray:root requirements.txt requirements.txt 
RUN pip install --no-cache-dir -r requirements.txt

# clean up apt
USER root 
RUN apt remove gcc g++ cmake -y && apt clean \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
USER ray

# Set environment
ENV PYTHONPATH /home/ray

# Put these at the end since they seem to upset the docker cache.
ARG BUILD_DATE
ARG GIT_COMMIT
LABEL build-date=$BUILD_DATE
LABEL git-commit=$GIT_COMMIT
